### PR TITLE
Super team picker

### PR DESCRIPTION
**Pull request by KenChukanit**
for adviser to review HW#4 Super Team Picker.

### CODE REVIEW

**Comment by tamaradesmith** [comment]
marked

notes:

1) bug in the knexfile.js, make to fix before I could run the migration, i had to move the closing bracket from line 12 to line 20.  you close development before you told knex where to look for the migrations files.

2) when creating teams should add all names to teams.

3) still should be able to see, edit and delete cohorts  on show page even after making teams .

**Comment by KenChukanit** [comment]
Hi Tamara

Should I fix what you advised and resend it to you? Or it is already been
marked.

Thanks
Ken

**Comment by tamaradesmith** [comment]
Already marked,  I try to give a few note for you to think about going
forwards, or fixes to bugs

**Comment by KenChukanit** [comment]
Ok Thank you so much.
I think I misunderstood on the show page when I see the example.
Have a great day

Ken

**Pull request merged**
